name: Reffy plugin build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Build project
      run: |
        npm install
        npm run build

    - name: Add artifacts to publish to the temp folder
      run: |
        mkdir downloads
        cp ./build/* ./downloads

    - name: Read version
      id: set_var
      run: |
        content=`cat ./downloads/manifest.json`
        content="${content//'%'/'%25'}"
        content="${content//$'\n'/'%0A'}"
        content="${content//$'\r'/'%0D'}"
        echo "::set-output name=packageJson::$content"

    - run: |
        echo "${{fromJson(steps.set_var.outputs.packageJson).version}}"

    - name: Use the Upload Artifact GitHub Action
      uses: actions/upload-artifact@v3
      with:
        name: Reffy plugin ${{fromJson(steps.set_var.outputs.packageJson).version}}
        path: downloads
